### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by davis68** [illinois/python-cheatsheet#1]
Looks great.

Can you fix a couple of typos:

- Quotes should all be straight, not autocorrected to curly.
- Clarify statements like `True and True = True` with either `==` or `→`.

Then I'll print & deploy in 101.

**Comment by davis68** [comment]
@edesaesilva making sure you see this :point_up: 

Thanks!

**Comment by edesaesilva** [comment]
Thank you! Corrections have been made (:
